### ISSUE TITLE
FF Extension not releasing proxy override after disabling

### ISSUE THREAD

**Issue by ctcarino** [LetheanMovement/lethean-browser-extension#12]
i have the extension installed but not running. today i want to change the proxy of the browser but the extension is not allowing me to do so. so naturally i will disable it. but after disabling it it wont allow me to change the proxy still. the proxy seetings are still grayed out

i think the best way for this is to have the extension release the proxy settings when its stopped so we dont have to disable the extension if we want to change proxies

**Comment by alfasoftpt** [comment]
@ctcarino Please open this issue in the correct project, which is https://github.com/LetheanMovement/lethean-browser-extension-ff

This issue is going to be closed as it is not related to the chrome extension
